name: Get new API version
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - "2.0"
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: composer install --no-dev

      - name: Download version Telegram API
        run: php console telegram:parse

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: 2.0

      - name: Generate Laravel version
        run: php console telegram:generate --extends=\\Spatie\\LaravelData\\Data

      - name: Get repository Telegram Bot cast for Laravel
        uses: actions/checkout@v4
        with:
          repository: 'mahlenko/telegram-bot-cast-laravel'
          path: 'repo'
          token: '${{ secrets.GH_PAT_LARAVEL_REPO }}'

      - name: Push laravel version
        run: |
          rm -rf repo/src
          mv build/Appto/TelegramBot repo/src
          cd repo
          git config --global user.email "${{ secrets.REPOSITORY_EMAIL }}"
          git config --global user.name "${{ github.actor }}"
          git add ./src/*
          git commit -m "[BOT] Update build version"
          git push
