name: Get new API version
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - "2.0"
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: composer install --no-dev

      - name: Download version Telegram API
        run: php console telegram:parse

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: 2.0

      - name: Generate PHP files
        run: php console telegram:generate --extends=\\Spatie\\LaravelData\\Data

      - name: Download telegram-bot-cast-laravel
        uses: actions/checkout@v4
        with:
          repository: 'mahlenko/telegram-bot-cast-laravel'
          path: 'repo'
          token: '${{ secrets.GH_PAT_LARAVEL_REPO }}'

      - name: Push generate files
        run: |
          mv build/Appto/TelegramBot repo/src/
          cd repo
          git commit -m "[BOT] Update version"
          git push

#      - name: Push generated files to telegram-bot-cast-laravel
#        uses: nkoppel/push-files-to-another-repository@v1.1.3
#        env:
#          API_TOKEN_GITHUB: ${{ secrets.GH_PAT_LARAVEL_REPO }}
#        with:
#          destination-branch: 'main'
#          source-files: 'build/Appto/TelegramBot/**/*.php '
#          destination-username: ${{ github.actor }}
#          destination-repository: 'telegram-bot-cast-laravel'
#          destination-directory: 'src'
#          commit-email: ${{ secrets.REPOSITORY_EMAIL }}
